services:
  - type: web
    name: ai-resume-analyzer-api
    env: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGODB_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: AI_API_KEY
        sync: false
      - key: AI_MODEL_NAME
        value: gemini-2.5-flash
      - key: PYTHON_VERSION
        value: "3.13"
      - key: FRONTEND_URL
        value: https://data-science-project-600u50ef6-murtaza231411it-2012.vercel.app
      - key: BACKEND_CORS_ORIGINS
        value: http://localhost:5173,http://127.0.0.1:5173,https://data-science-project-600u50ef6-murtaza231411it-2012.vercel.app